import transform from './transform';
import { defineTests } from './utils';

// maintain the sorted order
defineTests(transform, [
  'array-element',
  'array-nonempty',
  'array-schema',
  'array-validation-methods',
  'bigint-validation-methods',
  'coerce-bigint-schema',
  'coerce-boolean-schema',
  'coerce-date-schema',
  'coerce-number-schema',
  'coerce-string-schema',
  'date-validation-methods',
  'default',
  'default-import',
  'default-import-with-alias',
  'default-import-with-specific-alias',
  'describe',
  'discriminated-union-schema',
  'instanceof-schema',
  'literal-schema',
  'map-schema',
  'named-import',
  'named-import-with-alias',
  'named-import-with-specific-alias',
  'namespace-import',
  'native-enum',
  'nullable-schema',
  'nullish-schema',
  'number-validation-methods',
  'object-keyof',
  'object-omit',
  'object-partial',
  'object-passthrough',
  'object-pick',
  'object-required',
  'object-shape',
  'object-strict',
  'object-strip',
  'optional-schema',
  'parsing',
  'readonly',
  'record-schema',
  'schema-chain',
  'schema-options',
  'set-schema',
  'set-validation-methods',
  'specific-default-import',
  'specific-namespace-import',
  'string-validation-methods',
  'validation-error-msg',
  'zod-enum',
]);
