name: Deno CI

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.37.0"

      - name: Run Tests
        run: cd ./library && deno task test
