name: size
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4
      - uses: EskiMojo14/size-limit-action@v2
        with:
          directory: library
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm
          size_margin: non-zero
